### ISSUE TITLE
[Suggestions] Feature Requests

### ISSUE THREAD

**Issue by sinkda** [DomenikIrrgang/ClassicLFG#1]
Thanks for putting this addon together! Had a few suggestions in using it (currently in the Beta):

1.) Is it possible to close the window on Esc key?  This is done by adding the frame's name to the UISpecialFields table:

```lua
table.insert(UISpecialFrames, windowFrame:GetName());
```

2.) Is there a faster way to clear the selected dropdown's multi-select? If I have 4-5 selected and want to clear it there is no easy way to do this other than to unclick all of them.

3.) Perhaps a "fix" to #2, is there an "All" category? That just shows me all groups?  This would have to be removed from the dropdown for the "Create Group" tab. 

4.) Is there a checkbox or some feature that can be set to "Check Dungeons Out of my Level Range".  Would be helpful if im leveling an alt while looking for a dungeon group for my main / higher level alt.   You would still of course need to either change to your main to whisper the group or say "Hey I can bring my level XX YY and I can log over in Z minutes"

5.) Dropdowns match the input fields in look.  from this window it looks like the input field for invite message "invite please" is part of the dropdown for broadcast channel:

![image](https://user-images.githubusercontent.com/17501944/60021073-48dccc00-965f-11e9-8073-b853e65f636c.png)

That's all I have for now having just installed it.  I'll be sure to report any Lua errors etc too!

**Comment by DomenikIrrgang** [comment]
Hey thanks for your feedback, I really appreciate it!

#1 Yeah sure, thats not a problem, will be in for the next build!
#2 The UI you see right now is actually a complete rework that I just published yesterday, I will add the possibility to select and deselect all items at the same time!
#3 See #2
#4 I did not want to overwhelm people with a huge dungeon list, also some people might not know which dungeons to run on a given level. Experiences players don't need this hand-holding so I will make it an option in the settings menu!
#5 I realized this too, I am still trying to figure out how to properly make the dropdown items stand out a bit more without breaking the visual style, but a fix should come soon!

**Comment by DomenikIrrgang** [comment]
Out of curiosity, how did you get to know of this addon?

**Comment by DomenikIrrgang** [comment]
Update:
#1, #2, #3 and #4 are in, still trying to figure out what the best way to handle #5 is.
The new version should be available on curseforge/twitch by now

**Comment by sinkda** [comment]
Awesome :) Thanks!  I know you get a bad rep for being called "LFG" but hope there is a decent size of people to propagate information and make finding a group easier without having to stand in a city for an hour much easier :)

**Comment by DomenikIrrgang** [comment]
Even if you are the only user on the realm (which I hope is not going to be the case) you still have all the groups looking for people in a nicely organized window :)

**Comment by DomenikIrrgang** [comment]
Dropdown menus now have a slightly different color and should more recognizable now, closing this issue now!
