### ISSUE TITLE
Announce to several chats

### ISSUE THREAD

**Issue by Elmegaard** [DomenikIrrgang/ClassicLFG#102]
I often want to announce to Trade, World, LFG, and General chat, but the addon can only announce to one chat at the time. It's not so bad when you get to the higher levels where everyone joined the world chat, but the first 30 levels people tend not to do that (it seems).

**Comment by DomenikIrrgang** [comment]
The chat posting might be disabled on blizzards end in a future build, they did so on retail, still waiting on confirmation on it.
