### ISSUE TITLE
Weirdly formatted parties from channel LFG113V04a

### ISSUE THREAD

**Issue by d07RiV** [DomenikIrrgang/ClassicLFG#103]
Is it some new version of the addon that isn't out on curse? All of a sudden I'm getting these weird entries like `2,somename,1,lbrs,1,3,}lf1m blah blah blah` from channel LFG113V04a.

**Comment by DomenikIrrgang** [comment]
Thats not a bug in ClassicLFG but in a different Addon someone used that fucks up chat formatting.

**Comment by d07RiV** [comment]
I see, but why is it picking up messages from an chat channel for another addon?
