### ISSUE TITLE
That operation is not permitted in this channel

### ISSUE THREAD

**Issue by b-morgan** [DomenikIrrgang/ClassicLFG#108]
I'm getting this message in the General chat channel. I'm not currently looking to join any groups nor am I advertising a group to join. What is being sent constantly on that channel? Is there something I can do to stop it? Is there something YOU can do to stop it, please!

**Comment by b-morgan** [comment]
After some more research, I believe this is because ClassicLFG assumes that the ClassicLFG channel is channel 1. I believe which channel number is used for the ClassicLFG channel should be a selectable option. If that isn't possible, then put it on the highest channel number available, not the lowest.

As users, we should not have to re-train ourselves to use different channels that the commonly used defaults.

**Comment by DomenikIrrgang** [comment]
Original issue should not happen anymore.
