### ISSUE TITLE
ClassicLFG DM Post created error:

### ISSUE THREAD

**Issue by jlspeeddragon** [DomenikIrrgang/ClassicLFG#121]
here is the error code from someone who just created a post in the CLassicLFG to be broadcasted

> Message: SendChatMessage(): Invalid escape code in chat message
> Time: Sat Feb  1 11:00:17 2020
> Count: 2
> Stack: SendChatMessage(): Invalid escape code in chat message
> [C]: ?
> [C]: in function `SendChatMessage'
> ...ce\AddOns\ClassicLFG\src\networking\chat-network.lua:74: in function `SendMessage'
> ...ce\AddOns\ClassicLFG\src\networking\chat-network.lua:67: in function `SendObject'
> ...terface\AddOns\ClassicLFG\src\networking\network.lua:82: in function `SendObject'
> ...ace\AddOns\ClassicLFG\src\core\group-broadcaster.lua:24: in function <...ace\AddOns\ClassicLFG\src\core\group-broadcaster.lua:21>
> 
> Locals: (*temporary) = "CLFG_Network#tjlqjTp9#3#3#STitle^SLF~`Healer~`~|~`DM:E~`Jumpers!^SSource^T^SChannel^STrade~`-~`City^SType^SCHAT^t^SMembers^T^SItems^T^SHead^T^SIsHead^B^t^t^SSize^N0^t^t^t^^"
> (*temporary) = "CHANNEL"
> (*temporary) = nil
> (*temporary) = "5"

**Comment by DomenikIrrgang** [comment]
Fixed in newest version!
