### ISSUE TITLE
ChatNetwork.lua error

### ISSUE THREAD

**Issue by nsutcliffe** [DomenikIrrgang/ClassicLFG#124]
I sometimes get the following error. I was auto-running when I got this particular one (not interacting at all with WoW otherwise).

Date: 2020-04-10 15:22:10
ID: 2
Error occured in: AddOn: ClassicLFG
Count: 58
Message: Note: AddOn ClassicLFG attempted to call a protected function (UNKNOWN()) during combat lockdown.
Debug:
   [C]: ?
   [C]: SendChatMessage()
   ...ce\AddOns\ClassicLFG\src\networking\chat-network.lua:74: SendMessage()
   ...ce\AddOns\ClassicLFG\src\networking\chat-network.lua:67: SendObject()
   ...terface\AddOns\ClassicLFG\src\networking\network.lua:82: SendObject()
   ...ace\AddOns\ClassicLFG\src\core\group-broadcaster.lua:24:
      ...ace\AddOns\ClassicLFG\src\core\group-broadcaster.lua:21
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  WowheadLooter, v11304
  AdiBags, vDEV
  AtlasLootClassic, vv1.4.7
  AtlasLootClassicData, vv1.4.7
  AtlasLootClassicDungeonsAndRaids, vv1.4.7
  AtlasLootClassicMaps, vv1.0.0
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  AVQ, v28
  Bartender4, v4.9.0
  BastionEPGP, v1.3.4
  BattleInfo, v@project-version
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  ClassicAuraDurations, v
  ClassicCastbars, vv1.3.3
  ClassicCastbarsOptions, v
  ClassicLFG, v1.1.4
  Coordinates, v2.1.0
  DBMCore, v1.13.42
  DBMDefaultSkin, v
  DBMPartyClassic, v
  DBMStatusBarTimers, v
  DBMVPVEM, v10.0.0
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DungeonFinder, v0.1.7
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  ExtendedCharacterStats, v2.2.1
  FasterLooting, v1.1.2
  FishingBuddy, v0.7.3 Beta 4
  GatherLite, v@project-version@
  GatherMate2, v1.45.5
  GigaAutoResourcesTracker, v1.1.0
  Guidelime, v1.040
  GuidelimeJudgementAlliance160, v0.1339 beta
  HelloWorld, v0.1
  honorspy, v1.7.3
  HPH, v2.9
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  NovaWorldBuffs, v1.32
  Pawn, v2.3.24
  Questie, v5.10.0 0 fd3ff918
  SaySapped, v2019-08-27
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Spy, v1.0.24
  StandUp, v1.0.0
  Stubby, v8.2.6376 (SwimmingSeadragon)
  ThreatClassic2, v2.12
  TomCats, v0.0.2
  TomTom, vv11304-1.1.2
  TradeSkillMaster, vv4.9.32
  TradeSkillMasterAppHelper, vv4.0.8
  TranqRotate, v1.2.0
  UsedInRecipe, v1.0.3
  VendorPrice, v1.3.5
  WeakAuras, v2.16.6
  WeaponSwingTimer, v4.1.0
  ZygorGuidesViewerClassic, v1.0
  BlizRuntimeLib_enUS v1.13.4.11304 <none>
  (ck=7e0)

**Comment by DomenikIrrgang** [comment]
This was the result of calling SendChatMessage without a Hardware event. It has been fixed in the latest release.
