### ISSUE TITLE
UBRS

### ISSUE THREAD

**Issue by raymerjacque** [DomenikIrrgang/ClassicLFG#125]
You have lower black rock spire in the vanilla dungeon list, but there is no option for **Upper black rock spire**. Could you please add "upper black rock spire"

**Comment by DomenikIrrgang** [comment]
Make sure to reopen the menu after changing the settings. Is it still missing?

**Comment by raymerjacque** [comment]
No, there i no option in the list for "Upper BlackRock Spire, only Lower Blackrock Spire, Take a look at this screenshot below to see the problem : 

[](https://i.postimg.cc/qvCfdxtj/ubrs.png)

Now you see what i mean ?

**Comment by DomenikIrrgang** [comment]
Thisi not ClassicLFG, its a different Addon. I would recommend using it, the dungeon list is complete :)
