### ISSUE TITLE
Certain LFGs not being picked up

### ISSUE THREAD

**Issue by sinkda** [DomenikIrrgang/ClassicLFG#39]
For example:  "need tank WC" not being added to LFG window.

**Comment by DomenikIrrgang** [comment]
Right now that is intended, before the actual release of classic I'm going to expand parsing the chat messages. Ill post an update here once that is done!

**Comment by DomenikIrrgang** [comment]
The chat parsing is now a bit more lenient, but now LFG messages might pop up inbetween now like "tank looking for wc group" is going to show up, however messages like "need tank for wc" will show up now. The update will be released with the next update tonight.
