### ISSUE TITLE
Search Criteria not stored between windows

### ISSUE THREAD

**Issue by sinkda** [DomenikIrrgang/ClassicLFG#40]
If I hit select all and see some dungeons and close the window for a minute to do some other things and open the window again it doesn't keep my select all setting.  I have to click it again to add see the search results.

This is fine for select all but if im selecting only 3/4 dungeons then I have to go in and manually reselect those.

**Comment by DomenikIrrgang** [comment]
Right now that is a technical limitation. I'm currently working on a rework of the UI code to enable this.

**Comment by DomenikIrrgang** [comment]
The selected search is now stored properly between tabs and closing(opneing the window.
