### ISSUE TITLE
Blizzard breaking the LFG- Addon

### ISSUE THREAD

**Issue by kevinjpetersen** [DomenikIrrgang/ClassicLFG#65]
Hello Dom

I just wanted to let you know that Blizzard has implemented as patch to Classic which will break this addon.

I'm not here to diss or anything, even tho I don't like the idea of this Addon. Just wanted to make sure you know :)

https://blue.mmo-champion.com/topic/1107634-classiclfg-addon/

**Comment by Adyx16** [comment]
Same here. No ill intent, but seeing that Blizzard also does not agree with this kind of addons, please stop the development.
Cheers

**Comment by Borg123** [comment]
Actually, based on what the blue post says in the last paragraph:

> However, when an add-on goes beyond presenting information or providing aesthetic customization, and attempts to create an interconnected social network that relies on other players also using that same add-on, we are likely to scrutinize it particularly closely.

It seems like all that needs to be done is remove the addon to addon communication part and convert it into only using the chat parsing/posting. The chat parsing posting is not creating "an interconnected social network that relies on other players also using that same add-on." It would simply be parsing information and "presenting information or providing aesthetic customization."

**Comment by Adyx16** [comment]
Why nit and pick phrases and take them out of context just to try to go around it? Why do you jump over "we believe the nature of ClassicLFG is incompatible with our social design for Classic. Thus, in an upcoming patch (in the weeks following launch), we will be adding restrictions to the Classic add-on API that will significantly limit this add-on and others like it." ??? If people "need" these "quality of life" addons/features, then just play BFA. In vanilla there was no concept of "dungeon finder" so why bring it now?
Blizzard is going out of their way to patch the game so addons like this one will be incompatible...why would you keep pushing it?

**Comment by davidcraig** [comment]
I mean no offense to the author or anyone when I say this, but I am glad blizzard will block this addon, despite being an addon author myself and potentially having 1 less API to do cool stuff with - that's the price we pay when someone makes an addon like this

**Comment by Borg123** [comment]
> Why nit and pick phrases and take them out of context just to try to go around it?

It's not nick picking anything. They were specific in what made them make the decision to change something and that something can be changed without breaking the addon entirely. I hope the author makes those changes so the addon still functions even without the aspect that apparently was over a line for Blizzard.

They even say in the original blue post:

>that will significantly limit this add-on and others like it.

not break it entirely. They worded it carefully because they were clearly trying to placate the anti-addon nutjobs on the forums and make them happy, but they knew they weren't going to obliterate the addon completely. 

> If people "need" these "quality of life" addons/features, then just play BFA.

If you can't think of any reason why people would try two entirely different versions of the game that have a very long list of differences that have nothing to do with a GUI that makes it easier to sift through LFG messages, I'm not sure what to tell you, but maybe if you could figure it out if you tried. 

Nobody I know that's going to play classic would care one way or another about this addon. If the addon is changed to just parse and post in chat it's simply "presenting information or providing aesthetic customization," which is apparently fine with Blizzard and you'd just have to get over it.

**Comment by Adyx16** [comment]
Borg123 just stop. Yes you just read between the lines and only what you want. No, this addons has no place in classic. Go see the functionality of the old "Call to Arms" addon. If this one had the same functionality like that one, there wouldn't have been a problem.
Stop being a stubborn ignorant smart ass wannabe and get over yourself.
Thanks

**Comment by DomenikIrrgang** [comment]
Thanks for your post! I will still try to enabled as much of the functionality of the addon as possible with the upcoming changes. I'm going to close this issue now as it is not related to any bug/feature of the addon. If you want to provide further feedback or have a discussion, feel free to join the discord ;)

**Comment by EGDWind** [comment]
> 
> 
> Borg123 just stop. Yes you just read between the lines and only what you want. No, this addons has no place in classic. Go see the functionality of the old "Call to Arms" addon. If this one had the same functionality like that one, there wouldn't have been a problem.
> Stop being a stubborn ignorant smart ass wannabe and get over yourself.
> Thanks

I'm genuinely confused by this reply. You're saying the Call to Arms addon's functionality was fine (which I personally agree with). However, you're also disagreeing with Borg123, who's saying that ClassicLFG would still have a purpose even just as a glorified chat parser around mundane, manual LFG chat with a nice UI if addon-to-addon communication being removed is how Blizzard blocks the parts of this they don't approve of.

What Borg123 is describing is what Call to Arms *was*. It's main use (in my experience) was listing out normal LFG chat messages and letting you text search it for your specific dungeon. It also had its serverwide addon channel for letting other people with the addon be aware of your group, which may be *less* than what ClassicLFG can do now depending on Blizzard's plan of attack.

**Comment by Adyx16** [comment]
No clue what you're confused about. I literally just said "If this one (LFG) had the same functionality like that one(Call to Arms), there wouldn't have been a problem." So yea, if LFG had ONLY those functionalities and not tried to bring the "whole" RDF system into classic, would've been fine.
Anyway...I hope blizz devs will keep doing their best to block these unwanted addons.
