### ISSUE TITLE
Not showing new groups

### ISSUE THREAD

**Issue by Andoido1** [DomenikIrrgang/ClassicLFG#78]
So the addons only showing grps when i click CUSTOM.
anything else - it just doesnt show , for scarlet monestary even,

**Comment by WrobotProfiles** [comment]
Still having issues. Only CUSTOM will show groups.
 I have Scarlet Lib/Armory/Cath/GY Selected.. and in chat you can clearly see LFM SM xxx

https://i.imgur.com/L2UtV8t.jpg

**Comment by HelgeBecker** [comment]
Yes, same here.

Looking for a dungeon is impossible. You have to scan all custom entries by yourself, which is close to impossible to the sheer amount of non related posts. 

Best option is using the Bliz's SNG chan instead of this addon.

**Comment by HelgeBecker** [comment]
Edit: Uldaman works. Scarlet Monastery doesnt. I dont see the graveyard due level. Perhase its related with the gaveyard ussue

**Comment by cdmichaelb** [comment]
I've submitted a pull request that should resolve this issue.

**Comment by DomenikIrrgang** [comment]
the SM dungeon where not sorted in the correct categories and would always be listed under graveyard, thats why nothing was showing up for you in the addon, this should be fixed with the new update.
