### ISSUE TITLE
Scarlet Monastery problems

### ISSUE THREAD

**Issue by Mrjones81** [DomenikIrrgang/ClassicLFG#81]
Hello. All Scarlet Monastery groups made are automatically listed under graveyard, with no groups ever showing up under cathedral, armory or library. This means that once you're out of level range for Graveyard, you can no longer use ClassicLFG to find ANY scarlet monastery groups.

**Comment by cdmichaelb** [comment]
For a temporary fix you can check "Always show all dungeons" in settings. I've submitted a fix for this issue in pull requests and hopefully it'll be integrated soon.

**Comment by DomenikIrrgang** [comment]
Fixed.
