### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Seizzz** [DomenikIrrgang/ClassicLFG#86]
Date: 2019-09-18 11:43:05
ID: 2
Error occured in: Global
Count: 1
Message: ...\AddOns\ClassicLFG\src\gui\widgets\dropdown-menu.lua line 166:
   attempt to index field '?' (a nil value)
Debug:
   [C]: ?
   ...\AddOns\ClassicLFG\src\gui\widgets\dropdown-menu.lua:166: SetItems()
   ...face\AddOns\ClassicLFG\src\gui\settings\settings.lua:23: Callback()
   ClassicLFG\src\core\event-bus.lua:27: PublishEvent()
   ...rface\AddOns\ClassicLFG\src\core\channel-manager.lua:17:
      ...rface\AddOns\ClassicLFG\src\core\channel-manager.lua:14
Locals:

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AdvancedInterfaceOptions, v1.3.2
  AtlasLootClassic, vv1.1.11
  AucAdvanced, v8.2.6420 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.13
  Bartender4, v4.8.7
  BeanCounter, v8.2.6422 (SwimmingSeadragon)
  BetterAlign, v
  ClassicAutoDismount, v1.01
  ClassicCastbars, vv1.0.6
  ClassicCastbarsOptions, v
  ClassicLFG, v1.0.0
  DBMCore, v1.13.9
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsTinyThreat, v
  Enchantrix, v8.2.6411 (SwimmingSeadragon)
  GatherMate2, v1.45
  GTFO, v4.49.2
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemTooltipProfessionIcons, v1.1.1
  LeatrixPlus, v1.13.30
  MikScrollingBattleText, v5.7.149
  OmniCC, v8.2.4
  Pawn, v2.3.0 beta 1
  Prat30, v3.7.36
  Prat30Libraries, v
  Quartz, v3.5.1
  Quester, v1.13.2.1
  QuestFrameFixer, v1.1.1
  Questie, v4.1.1 BETA
  RealMobHealth, v2.11
  RepairMan, v1.0
  SexyMap, vv3-classic
  ShadowedUnitFrames, vv4.2-Classic-Beta7
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TipTac, v19.03.31
  TipTacItemRef, v19.03.31
  TitanClassic, v1.0.7.11302
  TitanClassicAmmo, v1.0.7.11302
  TitanClassicBag, v1.0.7.11302
  TitanClassicClock, v1.0.7.11302
  TitanClassicGold, v1.0.7.11302
  TitanClassicLocation, v1.0.7.11302
  TitanClassicLootType, v1.0.7.11302
  TitanClassicPerformance, v1.0.7.11302
  TitanClassicRepair, v1.0.7.11302
  TitanClassicVolume, v1.0.7.11302
  TitanClassicXP, v1.0.7.11302
  TomTom, vv11302-1.0.7
  TradeSkillMaster, vv4.8.8
  WeakAuras, v2.14.6
  WideQuestLog, v
  WideQuestLogLevels, v
  XLoot, v8.1-1
  XLootFrame, v8.1-1
  XLootGroup, v8.1-1
  XLootMaster, v8.1-1
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=7fb)

**Comment by DomenikIrrgang** [comment]
Thanks for the report, should be fixed now!
