### ISSUE TITLE
Suggestion: Show level and class of group leader next to their name

### ISSUE THREAD

**Issue by 9600bauds** [DomenikIrrgang/ClassicLFG#87]
Such as here:
![Wow_2019-09-18_21-02-04](https://user-images.githubusercontent.com/6526157/65197027-fd686d00-da57-11e9-8ff4-9de1abe6820f.png)

If it's even possible, I would find it very useful.

**Comment by DomenikIrrgang** [comment]
Cannot do that, restricted by the API.

**Comment by 9600bauds** [comment]
Sad but understandable
