### ISSUE TITLE
ClassicLFG make a popup window complaining there is a new version: 1.05 But there is not.

### ISSUE THREAD

**Issue by Altoholic** [DomenikIrrgang/ClassicLFG#91]

**Comment by Altoholic** [comment]
Also, as a twitch user, i use their tool to update all my addons, so even if there is a new version, i don't really care: the problem should be fixed with the next update.

**Comment by MightBeChris** [comment]
This.  I have edited the .lua file to remove it but turn it off.  There is no need for this.  Or dump it to chat at a minimum.

**Comment by cassianpry** [comment]
How to get 1.0.5 version? This annoying popup makes me crazy

**Comment by 9600bauds** [comment]
https://github.com/DomenikIrrgang/ClassicLFG/releases/

I believe this is an issue with CurseForge rather than with the addon.

**Comment by Natherul** [comment]
The addon really should be updated to curse and not just keep it here imho

**Comment by DomenikIrrgang** [comment]
There were some problems with curse that prevented me from uploading a new version. Some people took the latest from the github.
